name: base
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.12.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311hcd402e7_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.13.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.6.3=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311h8715677_1
  - bzip2=1.0.8=hf897c2e_4
  - c-ares=1.20.1=h31becfc_0
  - ca-certificates=2023.7.22=hcefe29a_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - certipy=0.1.3=py_0
  - cffi=1.16.0=py311h7963103_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - conda=23.9.0=py311hec3470c_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - configurable-http-proxy=4.6.0=h4e45a9e_0
  - cryptography=41.0.4=py311hd42d77a_0
  - debugpy=1.8.0=py311h8715677_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fmt=10.1.1=h2a328a1_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - greenlet=3.0.0=py311h8715677_1
  - icu=73.2=h787c7f5_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh2140261_0
  - ipython_genutils=0.2.0=py_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311hec3470c_3
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.4.0=pyhd8ed1ab_0
  - jupyter_core=5.4.0=py311hec3470c_0
  - jupyter_server=2.8.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyterhub=4.0.2=pyh31011fe_0
  - jupyterhub-base=4.0.2=pyh31011fe_0
  - jupyterlab=4.0.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.25.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h4e544f5_0
  - krb5=1.21.2=hc419048_0
  - ld_impl_linux-aarch64=2.40=h2d8c526_0
  - libarchive=3.7.2=h566b526_0
  - libcurl=8.4.0=h4e8248e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hd600fc2_1
  - libffi=3.4.2=h3557bc0_5
  - libgcc-ng=13.2.0=hf8544c7_2
  - libgomp=13.2.0=hf8544c7_2
  - libiconv=1.17=h9cdd2b7_0
  - libmamba=1.5.2=hea3be6c_0
  - libmambapy=1.5.2=py311h765b69a_0
  - libnghttp2=1.52.0=h250e5c5_0
  - libnsl=2.0.1=h31becfc_0
  - libsodium=1.0.18=hb9de7d4_1
  - libsolv=0.7.25=hd84c7bf_0
  - libsqlite=3.43.2=h194ca79_0
  - libssh2=1.11.0=h492db2e_0
  - libstdcxx-ng=13.2.0=h9a76618_2
  - libuuid=2.38.1=hb4cce97_0
  - libuv=1.46.0=h31becfc_0
  - libxml2=2.11.5=h3091e33_1
  - libzlib=1.2.13=h31becfc_5
  - lz4-c=1.9.4=hd600fc2_0
  - lzo=2.10=h516909a_1000
  - mako=1.2.4=pyhd8ed1ab_0
  - mamba=1.5.2=py311hb6c5aa6_0
  - markupsafe=2.1.3=py311hc8f2f60_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h2e1726e_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nodejs=20.8.1=hc1f8a26_0
  - notebook=7.0.6=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.1.3=h31becfc_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pamela=1.1.0=pyh1a96a4e_0
  - pandoc=3.1.3=h8af1aa0_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311hcd402e7_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311hcd402e7_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pycurl=7.45.1=py311h4769251_3
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.6=h43d1f9e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311hcd402e7_1
  - pyzmq=25.1.1=py311hc83961d_1
  - readline=8.2=h8fc344f_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - reproc=14.2.4.post0=h31becfc_0
  - reproc-cpp=14.2.4.post0=h2f0025b_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.6=py311h32437ce_0
  - ruamel.yaml=0.17.39=py311hcd402e7_0
  - ruamel.yaml.clib=0.2.7=py311hcd402e7_2
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.22=py311hc8f2f60_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h194ca79_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py311hc8f2f60_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h9cdd2b7_0
  - yaml=0.2.5=hf897c2e_2
  - yaml-cpp=0.8.0=h2f0025b_0
  - zeromq=4.3.5=h2f0025b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h31becfc_5
  - zstandard=0.21.0=py311hb827a26_1
  - zstd=1.5.5=h4c53e97_0
  - pip:
      - affine==2.4.0
      - altair==5.5.0
      - anyio==4.8.0
      - beautifulsoup4==4.12.3
      - bokeh==3.6.2
      - bqplot==0.12.30
      - branca==0.8.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colormath==3.0.0
      - contextily==1.6.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - faker==33.1.0
      - folium==0.19.3
      - fonttools==4.55.3
      - geodatasets==2024.8.0
      - geographiclib==2.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - imageio==2.36.1
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - joblib==1.4.2
      - jupyter-collaboration==2.1.2
      - jupyter-events==0.11.0
      - jupyter-server-fileid==0.9.3
      - jupyter-ydoc==2.1.1
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - matplotlib==3.10.0
      - mercantile==1.2.1
      - mpmath==1.3.0
      - narwhals==1.21.1
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.1.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - pulp==2.9.0
      - pyarrow==18.1.0
      - pycrdt==0.9.18
      - pycrdt-websocket==0.14.3
      - pygments==2.18.0
      - pygraphviz==1.14
      - pyogrio==0.10.0
      - pyparsing==3.2.1
      - pyproj==3.7.0
      - rasterio==1.3.11
      - regex==2024.11.6
      - requests==2.32.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - shapely==2.0.6
      - snuggs==1.4.7
      - sqlite-anyio==0.2.3
      - sympy==1.13.3
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - traitlets==5.14.3
      - traittypes==0.2.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - vega-datasets==0.9.0
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - xyzservices==2024.9.0
prefix: /opt/conda
